version: '3.8'
services:
  backend:
    build: ./backend  # Assuming your Dockerfile is in the backend directory
    ports:
      - "5000:80"  # Map a host port to the container's port 80
    environment:
      - NAME=World  # Example environment variable, though it's already set in Dockerfile

  frontend:
    build: ./frontend  # Assuming your Dockerfile is in the frontend directory
    ports:
      - "8080:80"  # Map a different host port to the container's port 80 to avoid conflict with backend
