name: Flask CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image for the backend
        run: docker build ./backend --file backend/Dockerfile --tag sullivlu21/flask_app:latest
      
      - name: Push the Docker image to Docker Hub
        run: docker push sullivlu21/flask_app:latest

  test-backend:
    needs: build-backend
    runs-on: ubuntu-latest

    steps:
      - name: Pull the Docker image from Docker Hub
        run: docker pull sullivlu21/flask_app:latest

      - name: Run tests
        run: docker run sullivlu21/flask_app:latest /bin/sh -c "pytest"

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image for the frontend
        run: docker build ./frontend --file frontend/Dockerfile --tag sullivlu21/frontend_app:latest

      - name: Push the Docker image to Docker Hub
        run: docker push sullivlu21/frontend_app:latest
      
