name: Flask CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for multi-platform
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: sullivlu21/flask_app:latest
          platforms: linux/amd64,linux/arm64

  test-backend:
    needs: build-backend
    runs-on: ubuntu-latest

    steps:
      - name: Pull the Docker image from Docker Hub
        run: docker pull sullivlu21/flask_app:latest

      - name: Run tests
        run: docker run sullivlu21/flask_app:latest /bin/sh -c "pytest"

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for the frontend (multi-platform)
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: sullivlu21/frontend_app:latest
          platforms: linux/amd64,linux/arm64
      
